import StoreProvider from "@/lib/store-provider";
import ApolloProvider from "@/lib/apollo-provider";
import { Nav } from "@/components/nav";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ApolloProvider>
            <Nav />
            {children}
          </ApolloProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
